DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS role CASCADE;

CREATE TYPE role AS ENUM ('ADMIN', 'CLIENT', 'OWNER', 'BROKER', 'EMPLOYEE');
ALTER TABLE "users" ALTER COLUMN "role" DROP NOT NULL;